#:kivy 1.11.0

ScreenManagement:
    ScreenOne:
    ScreenTwo:
        id: screen_two
    ScreenThree:

<ScreenOne>:
    BoxLayout:
        Button:
            text: "press me"
            on_release: root.manager.current = "two"    # every screen has a default property manager

<ScreenTwo>:
    name: "two"

    BoxLayout:
        id: container


<ScreenThree>:
    name: "three"

    BoxLayout:
        id: labelContainer

        Label:
            id: my_label
            text: ""